In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime 

from pandas.plotting import scatter_matrix
import warnings
warnings.filterwarnings("ignore")

from sklearn import preprocessing
from sklearn import model_selection

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/matteeussPei/Hotel-Booking-Demand/main/hotel_bookings.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
print('Total de variáveis:', df.shape[1])
print('Total de entradas:', df.shape[0])

Total de variáveis: 32
Total de entradas: 119390

In [4]:
df['is_canceled'].mean()

0.37041628277075134

In [5]:
pd.DataFrame({'tipo de dados':df.dtypes,
                'dados_ausentes(%)': (df.isnull().sum()/df.shape[0])*100,
                    'valores unicos': df.nunique()}).sort_values(by='dados_ausentes(%)', ascending=False)

,tipo de dados,dados_ausentes(%),valores unicos
company,float64,94.306893,352
agent,float64,13.686238,333
country,object,0.408744,177
children,float64,0.003350,5
reserved_room_type,object,0.000000,10
assigned_room_type,object,0.000000,12
booking_changes,int64,0.000000,21
deposit_type,object,0.000000,3
hotel,object,0.000000,2
previous_cancellations,int64,0.000000,15
days_in_waiting_list,int64,0.000000,128
customer_type,object,0.000000,4
adr,float64,0.000000,8879
required_car_parking_spaces,int64,0.000000,5
total_of_special_requests,int64,0.000000,6
reservation_status,object,0.000000,3
previous_bookings_not_canceled,int64,0.000000,73
is_repeated_guest,int64,0.000000,2
is_canceled,int64,0.000000,2
distribution_channel,object,0.000000,5
market_segment,object,0.000000,8
meal,object,0.000000,5
babies,int64,0.000000,5
adults,int64,0.000000,14
stays_in_week_nights,int64,0.000000,35
stays_in_weekend_nights,int64,0.000000,17
arrival_date_day_of_month,int64,0.000000,31
arrival_date_week_number,int64,0.000000,53
arrival_date_month,object,0.000000,12
arrival_date_year,int64,0.000000,3
lead_time,int64,0.000000,479
reservation_status_date,object,0.000000,926

In [6]:
df.drop(columns = ['agent', 'company'], inplace=True)

In [7]:
pd.DataFrame({'tipo de dados':df.dtypes,
                'dados_ausentes(%)': (df.isnull().sum()/df.shape[0])*100,
                    'valores unicos': df.nunique()}).sort_values(by='dados_ausentes(%)', ascending=False)

,tipo de dados,dados_ausentes(%),valores unicos
country,object,0.408744,177
children,float64,0.003350,5
hotel,object,0.000000,2
is_repeated_guest,int64,0.000000,2
reservation_status,object,0.000000,3
total_of_special_requests,int64,0.000000,6
required_car_parking_spaces,int64,0.000000,5
adr,float64,0.000000,8879
customer_type,object,0.000000,4
days_in_waiting_list,int64,0.000000,128
deposit_type,object,0.000000,3
booking_changes,int64,0.000000,21
assigned_room_type,object,0.000000,12
reserved_room_type,object,0.000000,10
previous_bookings_not_canceled,int64,0.000000,73
previous_cancellations,int64,0.000000,15
distribution_channel,object,0.000000,5
is_canceled,int64,0.000000,2
market_segment,object,0.000000,8
meal,object,0.000000,5
babies,int64,0.000000,5
adults,int64,0.000000,14
stays_in_week_nights,int64,0.000000,35
stays_in_weekend_nights,int64,0.000000,17
arrival_date_day_of_month,int64,0.000000,31
arrival_date_week_number,int64,0.000000,53
arrival_date_month,object,0.000000,12
arrival_date_year,int64,0.000000,3
lead_time,int64,0.000000,479
reservation_status_date,object,0.000000,926

In [8]:
df.drop(columns=['country', 'arrival_date_year', 'reservation_status', 'arrival_date_month'], inplace = True)

In [9]:
df = df.dropna(subset = ['children']).reset_index(drop=True)

In [10]:
filtro = (df['babies'] == 0) & (df['children'] == 0) & (df['adults'] == 0)
df = df[~filtro]

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,Resort Hotel,0,342,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015-07-01
1,Resort Hotel,0,737,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015-07-01
2,Resort Hotel,0,7,27,1,0,1,1,0.0,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
3,Resort Hotel,0,13,27,1,0,1,1,0.0,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
4,Resort Hotel,0,14,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015-07-03

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85427 entries, 0 to 119385
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85427 non-null  object
 1   is_canceled                     85427 non-null  int64
 2   lead_time                       85427 non-null  int64
 3   arrival_date_week_number        85427 non-null  int64
 4   arrival_date_day_of_month       85427 non-null  int64
 5   stays_in_weekend_nights         85427 non-null  int64
 6   stays_in_week_nights            85427 non-null  int64
 7   adults                          85427 non-null  int64
 8   children                        85427 non-null  float64
 9   babies                          85427 non-null  int64
 10  meal                            85427 non-null  object
 11  market_segment                  85427 non-null  object
 12  distribution_channel            85427 non-null  object
 13  is_repeated_guest               85427 non-null  int64
 14  previous_cancellations          85427 non-null  int64
 15  previous_bookings_not_canceled  85427 non-null  int64
 16  reserved_room_type              85427 non-null  object
 17  assigned_room_type              85427 non-null  object
 18  booking_changes                 85427 non-null  int64
 19  deposit_type                    85427 non-null  object
 20  days_in_waiting_list            85427 non-null  int64
 21  customer_type                   85427 non-null  object
 22  adr                             85427 non-null  float64
 23  required_car_parking_spaces     85427 non-null  int64
 24  total_of_special_requests       85427 non-null  int64
 25  reservation_status_date         85427 non-null  object
dtypes: float64(2), int64(15), object(9)
memory usage: 17.6+ MB

In [14]:
df['children'] = df['children'].astype('int64', errors='raise')

In [15]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

df['year'] = df['reservation_status_date'].dt.year
df['month'] = df['reservation_status_date'].dt.month
df['day'] = df['reservation_status_date'].dt.day
df.drop(columns=['reservation_status_date'], inplace=True)

In [16]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,year,month,day
0,Resort Hotel,0,342,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015,7,1
1,Resort Hotel,0,737,27,1,0,0,2,0,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015,7,1
2,Resort Hotel,0,7,27,1,0,1,1,0,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015,7,2
3,Resort Hotel,0,13,27,1,0,1,1,0,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015,7,2
4,Resort Hotel,0,14,27,1,0,2,2,0,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015,7,3

In [17]:
cat_cols = [col for col in df.columns if df[col].dtype == 'O']

In [18]:
cat_cols.append('year')
cat_cols.append('month')
cat_cols.append('day')

In [19]:
cat_cols

['hotel',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'year',
 'month',
 'day']

In [20]:
cat_var = df[cat_cols]
cat_var.head()

,hotel,meal,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,year,month,day
0,Resort Hotel,BB,Direct,Direct,C,C,No Deposit,Transient,2015,7,1
1,Resort Hotel,BB,Direct,Direct,C,C,No Deposit,Transient,2015,7,1
2,Resort Hotel,BB,Direct,Direct,A,C,No Deposit,Transient,2015,7,2
3,Resort Hotel,BB,Corporate,Corporate,A,A,No Deposit,Transient,2015,7,2
4,Resort Hotel,BB,Online TA,TA/TO,A,A,No Deposit,Transient,2015,7,3

In [21]:
X = df.drop(columns=['is_canceled'], axis = 1)
y = df['is_canceled']
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, stratify= y,test_size = 0.2,random_state=42)

In [22]:
le = preprocessing.LabelEncoder()

In [25]:
X_train.head()

,hotel,lead_time,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,year,month,day
100085,0,27,43,20,0,3,2,0,1,0,5,3,0,0,0,0,3,0,0,0,2,85.00,0,1,2,9,22
18875,1,159,20,8,2,2,2,0,0,0,6,3,0,1,0,5,5,0,0,0,2,88.20,0,0,1,11,1
23485,1,123,18,24,2,0,2,0,0,3,3,1,0,0,0,3,8,0,0,0,2,0.00,1,0,2,3,25
72791,0,318,32,6,2,5,2,0,0,0,5,3,0,0,0,0,0,0,0,0,2,80.10,0,0,3,7,5
91535,0,44,26,22,0,1,2,0,0,0,6,3,0,0,0,0,0,0,0,0,2,87.31,0,1,2,5,22

In [24]:
X_train[cat_cols] = X_train[cat_cols].apply(le.fit_transform)
X_test[cat_cols] = X_test[cat_cols].apply(le.transform)

ValueError: invalid literal for int() with base 10: 'Resort Hotel'

In [ ]:
X_train.head()

In [ ]:
df.info()

## StandartScale

In [ ]:
df.var()

In [ ]:
df.head()

In [ ]:
cat_var = df[cat_cols]
cat_var.head()

In [ ]:
num_cols = df.drop(columns=cat_cols)
num_cols.head()

In [ ]:
#num_cols['arrival_date_day_of_month'] =

In [ ]:
from sklearn.preprocessing import StandardScaler
sca = StandardScaler()
X_temp= sca.fit_transform(num_cols)
X_temp = pd.DataFrame(X_temp, columns= num_cols.columns)

In [ ]:
X_temp.head()

In [ ]:
frames = [cat_var, X_temp]

In [ ]:
df = pd.concat([cat_var.reset_index(drop=True), X_temp.reset_index(drop=True)], axis = 1)

In [ ]:
df.head()

In [ ]:
X = df.drop(columns = 'is_canceled')
y = df['is_canceled']

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
for model in [LogisticRegression, RandomForestClassifier, XGBClassifier]:
    cls = model()
    cls.fit(X_train, y_train)
    previsao = cls.predict(X_test)

    name = cls.__class__.__name__
    acuracia = (accuracy_score(y_test, previsao)*100).round(2)
    print(f'{name} - Acurácia: {acuracia}%')
    print('='*30)
    clf_report = classification_report(y_test, previsao)
    print(f"Classification Report : \n{clf_report}")
    print()
    print()